## Задание 1.1

In [ ]:
import numpy as np

In [20]:
a = [i for i in range(12,24)]

In [28]:
b = np.array(a)
b

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [42]:
b.reshape(3,4)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [30]:
b.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [31]:
b.reshape(1,12)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [32]:
b.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [33]:
b.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [36]:
b.reshape(4,-1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [37]:
b.reshape(3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
b.reshape(6,-1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [40]:
b.reshape(-1,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [41]:
b.reshape(-1,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [44]:
# Массив из 1 столбца и 12 строк не одномерный


## Задание 1.2

In [49]:
#Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения  
#со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
a = np.random.randn(3,4)
a

array([[ 1.66301642, -0.15747525, -0.96031964,  2.50299694],
       [-0.69666668,  0.41441522,  0.1736815 , -0.73623974],
       [ 0.37536509, -0.30698365,  0.57388683,  0.39011836]])

In [53]:
#Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
a.reshape(a.size)

array([ 1.66301642, -0.15747525, -0.96031964,  2.50299694, -0.69666668,
        0.41441522,  0.1736815 , -0.73623974,  0.37536509, -0.30698365,
        0.57388683,  0.39011836])

## Задание 1.3

In [61]:
#Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. 
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [62]:
#Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
#В чем разница между массивами a и b?

## Задание 1.4

In [103]:
#Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
#чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [107]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [109]:
v = np.vstack((a, b))
v.size

10

In [110]:
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## Задание 1.5

In [74]:
#Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [75]:
#Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
#Получить матрицу At путем транспонирования матрицы A.
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [84]:
#Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [149]:
#Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
B.size
#b_inv = np.linalg.inv(B)
#b_inv

16

## Задание 1.6

In [81]:
#Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
np.random.seed(42)
#Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 
#0 до 16 невключительно. 
c = np.random.randint(0,16,16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [83]:
#Поменяйте его форму так, чтобы получилась квадратная матрица C. 
C = c.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [87]:
#Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
D = B + (C * 10)
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [88]:
#Вычислите определитель, ранг и обратную матрицу D_inv для D.
np.linalg.det(D)

-28511999.999999944

In [89]:
np.linalg.matrix_rank(D)

4

In [90]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

## Задание 1.7

In [115]:
#Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
#Убедитесь, что в матрице D_inv остались только нули и единицы. 
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [117]:
#С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, 
#получите матрицу E размером 4x4. 
#Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему 
#элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, 
#должны быть равны соответствующему элементу матрицы C.
E = np.where([D_inv],B,C)
E

array([[[  5,  14,  23,  14],
        [ 10,   7,  12, 122],
        [  6,   9,   2, 212],
        [ 32,  10, 212,   4]]])

## Задание 2

In [127]:
#Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
#Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
#Будем считать, что каждый столбец - это признак, а строка - наблюдение.
#Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
#Результат запишите в массив mean_a, в нем должно быть 2 элемента.
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [129]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

## Задание 3

In [133]:
#Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, 
#содержащиеся в массиве mean_a.
#Вычисление должно производиться в одно действие.
#Получившийся массив должен иметь размер 5x2.
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 4

In [140]:
#Найдите скалярное произведение столбцов массива a_centered.
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
#В результате должна получиться величина a_centered_sp. 
a_centered_sp

8.0

In [147]:
#Затем поделите a_centered_sp на N-1, где N - число наблюдений.
N = a_centered.shape
N = N[0]
N

5

In [148]:
a_centered_sp / (N-1)

2.0